feat(content-server): Enable gzip for html and static resources on the content server
mozilla/fxa-dev pull request #383
Opened 2018-06-29 11:01 UTC by shane-tomlinson

This should better approximate prod and ship ~ 1/2 the bytes down the wire.

@vladikoff, @jrgm or @jbuck - r?

2018-07-09 17:49 UTC, jrgm requested changes
Differences:
 - prod gzip_comp_level is 1, not 6
 - gzip_buffers - perhaps gzip_buffers 32 4k to match PAGESIZE
 - gzip_min_length 1100 vs. default 20
 - gzip_types
   - prod is:
      application/javascript;                                                                                                               
      application/json                                                                                                                      
      application/x-javascript                                                                                                              
      application/xml                                                                                                                       
      application/xml+rss                                                                                                                   
      text/css                                                                                                                              
      text/javascript                                                                                                                       
      text/plain                                                                                                                            
      text/xml                                                                                                                              
                                                                                                                                            
I think the gzip_comp_level and gzip_min_length make sense (90% of the compression in doing any compression at all; don't gzip if you won't save packets). On gzip_types, up to you, and if prod should change, let me know.

2018-07-09 18:17 UTC, jrgm commented
Also, prod has an includes/gzip.conf and does `include includes/gzip.conf`. Could do the same, and include it in each `server` block, but given the gzip_min_size, most api responses wouldn't be compressed anyways.

2018-07-17 11:06 UTC, shane-tomlinson commented
@jrgm - updated!

2018-07-19 04:39 UTC, jrgm approved these changes

2018-07-19 09:50 UTC, merged